# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 22:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorrequests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorrequest',
            name='cram',
        ),
        migrations.RemoveField(
            model_name='tutorrequest',
            name='student',
        ),
        migrations.RemoveField(
            model_name='tutorrequest',
            name='tutor',
        ),
        migrations.DeleteModel(
            name='Cram',
        ),
        migrations.DeleteModel(
            name='TutorRequest',
        ),
    ]
