# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 22:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tutorrequests', '0002_auto_20170720_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateStart', models.DateTimeField(null=True)),
                ('dateEnd', models.DateTimeField(null=True)),
                ('multiplier', models.DecimalField(decimal_places=3, max_digits=4)),
                ('location', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TutorRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancelled', models.NullBooleanField()),
                ('student_accept', models.NullBooleanField()),
                ('tutor_accept', models.NullBooleanField()),
                ('student_cancel', models.NullBooleanField()),
                ('tutor_cancel', models.NullBooleanField()),
                ('answer_date', models.DateTimeField(null=True)),
                ('building', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('help_description', models.CharField(max_length=300)),
                ('subject', models.CharField(max_length=50)),
                ('type_help', models.CharField(max_length=50)),
                ('dateTime', models.DateTimeField(null=True)),
                ('timeElapsed', models.DateTimeField(null=True)),
                ('amount', models.DecimalField(decimal_places=10, default=0, max_digits=11)),
                ('cram', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorrequests.Cram')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_request', to=settings.AUTH_USER_MODEL)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_reqest', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
