# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-30 23:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0003_auto_20170730_2317'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('S', 'Son'), ('D', 'Daughter'), ('NC', 'Niece'), ('NP', 'Nephew'), ('GS', 'Grandson'), ('GD', 'Granddaughter')], default='S', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('M', 'Mother'), ('F', 'Father'), ('A', 'Aunt'), ('U', 'Uncle'), ('GM', 'Grandmother'), ('GF', 'Grandfather')], default='M', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(default='1997-07-28')),
                ('pro_pic', models.ImageField(blank=True, upload_to='')),
                ('child', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Child')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Family')),
                ('guardian', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Guardian')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
