# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('users', '0002_userprofile_pro_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='major',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='major',
            field=models.ManyToManyField(to='common.Major'),
        ),
    ]
