# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170630_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='major',
            field=models.ManyToManyField(related_name='majors', to='common.Major'),
        ),
    ]
