# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-31 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('charge_type',
                 models.CharField(choices=[('FO', 'Food'), ('CL', 'Clothing'), ('EN', 'Entertainment'), ('O', 'Other')],
                                  default='O', max_length=2)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
    ]
