# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-23 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0008_userprofile_chore_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=40)),
                ('notify', models.ManyToManyField(to='users.UserProfile')),
            ],
        ),
    ]
