# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-23 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userprofile_chore_points'),
        ('notifications', '0002_notification_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_read',
        ),
        migrations.AddField(
            model_name='notification',
            name='read_by',
            field=models.ManyToManyField(related_name='read_by', to='users.UserProfile'),
        ),
    ]
