# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-23 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_auto_20171023_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notify',
            field=models.ManyToManyField(related_name='notify', to='users.UserProfile'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='read_by',
            field=models.ManyToManyField(to='users.UserProfile'),
        ),
    ]
