# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-23 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_auto_20171023_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='read_by',
            field=models.ManyToManyField(blank=True, to='users.UserProfile'),
        ),
    ]
