# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-23 20:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_auto_20171023_0543'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
