# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-25 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userprofile_chore_points'),
        ('common', '0007_auto_20171024_1810'),
        ('notifications', '0010_auto_20171023_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('family', models.ManyToManyField(to='common.Family')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile')),
            ],
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notify',
        ),
        migrations.AddField(
            model_name='notification',
            name='notify',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='notify', to='users.UserProfile'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='notification',
            name='read_by',
        ),
        migrations.AddField(
            model_name='notification',
            name='read_by',
            field=models.ForeignKey(blank=True, default=2, on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile'),
            preserve_default=False,
        ),
    ]
