# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-25 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userprofile_chore_points'),
        ('notifications', '0011_auto_20171025_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='notify',
        ),
        migrations.AddField(
            model_name='notification',
            name='notify',
            field=models.ManyToManyField(related_name='notify', to='users.UserProfile'),
        ),
        migrations.RemoveField(
            model_name='notification',
            name='read_by',
        ),
        migrations.AddField(
            model_name='notification',
            name='read_by',
            field=models.ManyToManyField(blank=True, to='users.UserProfile'),
        ),
    ]
