# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-25 14:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0012_auto_20171025_1420'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
    ]
