# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-25 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0014_auto_20171025_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(to='notifications.Comment'),
        ),
    ]
