# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-25 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0014_chorereward_is_redeemed'),
        ('finances', '0006_remove_charge_post'),
        ('events', '0001_initial'),
        ('notifications', '0016_auto_20171025_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.Charge')),
                ('chore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chores.Chore')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(to='notifications.Comment'),
        ),
        migrations.AddField(
            model_name='post',
            name='app_event',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='notifications.AppEvent'),
        ),
    ]
